// Code generated by cli/generator/entity/gen.go; DO NOT EDIT.

package master

import (
	"app/domain/value/master"
	"time"
)

type DictionaryMasters []DictionaryMaster

type DictionaryMaster struct {
	Key       master.DictionaryKey `json:"key,string" gorm:"column:key;type:varchar(255)"`
	Ja        string               `json:"ja" gorm:"column:ja"`
	En        string               `json:"en" gorm:"column:en"`
	CreatedAt time.Time            `json:"-" gorm:"-;autoCreateTime"`
	UpdatedAt time.Time            `json:"-" gorm:"-;autoUpdateTime"`
}

func (e *DictionaryMaster) TableName() string {
	return "dictionary_master"
}
