// Code generated by cli/generator/entity/gen.go; DO NOT EDIT.

package master

import (
	"app/domain/value/master"
	"time"
)

type ScheduleMasters []ScheduleMaster

type ScheduleMaster struct {
	ID        master.ScheduleId `json:"id,int" gorm:"column:id;type:int"`
	StartAt   time.Time         `json:"start_at" gorm:"column:start_at"`
	EndAt     time.Time         `json:"end_at" gorm:"column:end_at"`
	CloseAt   time.Time         `json:"close_at" gorm:"column:close_at"`
	CreatedAt time.Time         `json:"-" gorm:"-;autoCreateTime"`
	UpdatedAt time.Time         `json:"-" gorm:"-;autoUpdateTime"`
}

func (e *ScheduleMaster) TableName() string {
	return "schedule_master"
}
