// Code generated by cli/generator/enum/gen.go; DO NOT EDIT.

package item

type ItemType int

const (
	ItemTypeNone ItemType = iota
	ItemTypeConsume
	ItemTypeMaterial
)

func (e ItemType) ToString() string {
	names := [...]string{"ItemTypeNone", "ItemTypeConsume", "ItemTypeMaterial"}
	if e < ItemTypeNone || e > ItemTypeMaterial {
		return "Unknown"
	}

	return names[e]
}
