// Code generated by cli/generator/enum/gen.go; DO NOT EDIT.

package item

type ItemEffectType int

const (
	ItemEffectTypeNone ItemEffectType = iota
	ItemEffectTypeRecoverStamina
	ItemEffectTypeAddUserExp
)

func (e ItemEffectType) ToString() string {
	names := [...]string{"ItemEffectTypeNone", "ItemEffectTypeRecoverStamina", "ItemEffectTypeAddUserExp"}
	if e < ItemEffectTypeNone || e > ItemEffectTypeAddUserExp {
		return "Unknown"
	}

	return names[e]
}
