// Code generated by cli/generator/repoistory/gen.go; DO NOT EDIT.
//go:generate mockgen -source=./dictionary_master_repository.gen.go -destination=./dictionary_master_repository_mock.gen.go -package=master

package master

import (
	master_entity "app/domain/entity/master"
	master_value "app/domain/value/master"
	"github.com/gin-gonic/gin"
)

type DictionaryMasterRepository interface {
	FindByKey(c *gin.Context, key master_value.DictionaryKey) (*master_entity.DictionaryMaster, error)

	Save(c *gin.Context, entity master_entity.DictionaryMaster) error
}
