// Code generated by cli/generator/repoistory/gen.go; DO NOT EDIT.
//go:generate mockgen -source=./item_master_repository.gen.go -destination=./item_master_repository_mock.gen.go -package=master

package master

import (
	master_entity "app/domain/entity/master"
	master_value "app/domain/value/master"
	"github.com/gin-gonic/gin"
)

type ItemMasterRepository interface {
	FindByID(c *gin.Context, id master_value.ItemId) (*master_entity.ItemMaster, error)

	Save(c *gin.Context, entity master_entity.ItemMaster) error
}
