// Code generated by cli/generator/repoistory/gen.go; DO NOT EDIT.
//go:generate mockgen -source=./schedule_master_repository.gen.go -destination=./schedule_master_repository_mock.gen.go -package=master

package master

import (
	master_entity "app/domain/entity/master"
	master_value "app/domain/value/master"
	"github.com/gin-gonic/gin"
)

type ScheduleMasterRepository interface {
	FindByID(c *gin.Context, id master_value.ScheduleId) (*master_entity.ScheduleMaster, error)

	Save(c *gin.Context, entity master_entity.ScheduleMaster) error
}
