// Code generated by cli/generator/vo/gen.go; DO NOT EDIT.

package master

import (
	"app/domain/value"
	"encoding/json"
	"fmt"
)

type AccumulateId struct {
	value.ValueObject[int64]
}

func NewAccumulateId(v int64) AccumulateId {
	return AccumulateId{value.NewValueObject[int64](v)}
}

func (v *AccumulateId) Scan(value interface{}) error {
	switch vt := value.(type) {
	case int64:
		*v = NewAccumulateId(vt)

	default:
		return fmt.Errorf("invalid type. type=%s", vt)
	}
	return nil
}

func (v *AccumulateId) UnmarshalJSON(data []byte) error {
	var t any
	if err := json.Unmarshal(data, &t); err != nil {
		return err
	}

	switch t.(type) {
	case float64:
		v.Scan(int64(t.(float64)))
		return nil
	}

	v.Scan(t)
	return nil
}
