// Code generated by cli/generator/vo/gen.go; DO NOT EDIT.

package master

import (
	"app/domain/value"
	"encoding/json"
	"fmt"
)

type DictionaryKey struct {
	value.ValueObject[string]
}

func NewDictionaryKey(v string) DictionaryKey {
	return DictionaryKey{value.NewValueObject[string](v)}
}

func (v *DictionaryKey) Scan(value interface{}) error {
	switch vt := value.(type) {
	case string:
		*v = NewDictionaryKey(vt)

	default:
		return fmt.Errorf("invalid type. type=%s", vt)
	}
	return nil
}

func (v *DictionaryKey) UnmarshalJSON(data []byte) error {
	var t any
	if err := json.Unmarshal(data, &t); err != nil {
		return err
	}

	v.Scan(t)
	return nil
}
