// Code generated by cli/generator/entity/gen.go; DO NOT EDIT.

package user

import (
	"app/domain/value/user"
	"time"
)

type Users []User

type User struct {
	ID                     user.UserId `json:"id,string" gorm:"column:id;type:varchar(255)"`
	Name                   string      `json:"name" gorm:"column:name"`
	Stamina                uint64      `json:"stamina" gorm:"column:stamina"`
	StaminaLatestUpdatedAt time.Time   `json:"stamina_latest_updated_at" gorm:"column:stamina_latest_updated_at"`
	Coin                   uint64      `json:"coin" gorm:"column:coin"`
	LatestLoggedInAt       time.Time   `json:"latest_logged_in_at" gorm:"column:latest_logged_in_at"`
	CreatedAt              time.Time   `json:"-" gorm:"-;autoCreateTime"`
	UpdatedAt              time.Time   `json:"-" gorm:"-;autoUpdateTime"`
}

func (e *User) TableName() string {
	return "user"
}
