// Code generated by cli/generator/entity/gen.go; DO NOT EDIT.

package user

import (
	"app/domain/value/master"
	"app/domain/value/user"
	"time"
)

type UserItems []UserItem

type UserItem struct {
	UserId    user.UserId   `json:"user_id,string" gorm:"column:user_id;type:varchar(255)"`
	ItemId    master.ItemId `json:"item_id,int" gorm:"column:item_id;type:int"`
	Quantity  uint64        `json:"quantity" gorm:"column:quantity"`
	CreatedAt time.Time     `json:"-" gorm:"-;autoCreateTime"`
	UpdatedAt time.Time     `json:"-" gorm:"-;autoUpdateTime"`
}

func (e *UserItem) TableName() string {
	return "user_item"
}
