// Code generated by cli/generator/entity/gen.go; DO NOT EDIT.

package user

import (
	"app/domain/value/user"
	"time"
)

type UserAuths []UserAuth

type UserAuth struct {
	UserId    user.UserId `json:"user_id,string" gorm:"column:user_id;type:varchar(255)"`
	Token     string      `json:"token" gorm:"column:token"`
	ExpiredAt time.Time   `json:"expired_at" gorm:"column:expired_at"`
	CreatedAt time.Time   `json:"-" gorm:"-;autoCreateTime"`
	UpdatedAt time.Time   `json:"-" gorm:"-;autoUpdateTime"`
}

func (e *UserAuth) TableName() string {
	return "user_auth"
}
