// Code generated by cli/generator/repoistory/gen.go; DO NOT EDIT.
//go:generate mockgen -source=./user_item_repository.gen.go -destination=./user_item_repository_mock.gen.go -package=user

package user

import (
	user_entity "app/domain/entity/user"
	master_value "app/domain/value/master"
	user_value "app/domain/value/user"
	"github.com/gin-gonic/gin"
)

type UserItemRepository interface {
	FindByUserIdAndItemId(c *gin.Context, user_id user_value.UserId, item_id master_value.ItemId) (*user_entity.UserItem, error)

	FindByUserId(c *gin.Context, user_id user_value.UserId) (*user_entity.UserItems, error)

	Save(c *gin.Context, entity user_entity.UserItem) error
}
