// Code generated by cli/generator/repoistory/gen.go; DO NOT EDIT.
//go:generate mockgen -source=./user_repository.gen.go -destination=./user_repository_mock.gen.go -package=user

package user

import (
	user_entity "app/domain/entity/user"
	user_value "app/domain/value/user"
	"github.com/gin-gonic/gin"
)

type UserRepository interface {
	FindByID(c *gin.Context, id user_value.UserId) (*user_entity.User, error)

	Save(c *gin.Context, entity user_entity.User) error
}
