// Code generated by cli/generator/repoistory/gen.go; DO NOT EDIT.
//go:generate mockgen -source=./user_present_repository.gen.go -destination=./user_present_repository_mock.gen.go -package=user

package user

import (
	user_entity "app/domain/entity/user"
	user_value "app/domain/value/user"
	"github.com/gin-gonic/gin"
	"time"
)

type UserPresentRepository interface {
	FindByID(c *gin.Context, id user_value.PresentId) (*user_entity.UserPresent, error)

	FindByUserIdAndArriveDateAndLimitDateAndReceivedAt(c *gin.Context, user_id user_value.UserId, arrive_date time.Time, limit_date time.Time, received_at time.Time) (*user_entity.UserPresents, error)

	Save(c *gin.Context, entity user_entity.UserPresent) error
}
