// Code generated by cli/generator/enum/gen.go; DO NOT EDIT.

package error

type ErrorCode int

const (
	ErrorCodeNone ErrorCode = iota
	ErrorCodeUserNotFound
)

func (e ErrorCode) ToString() string {
	names := [...]string{"ErrorCodeNone", "ErrorCodeUserNotFound"}
	if e < ErrorCodeNone || e > ErrorCodeUserNotFound {
		return "Unknown"
	}

	return names[e]
}
