// Code generated by cli/generator/enum/gen.go; DO NOT EDIT.

package present

type ContentType int

const (
	ContentTypeNone ContentType = iota
	ContentTypeItem
)

func (e ContentType) ToString() string {
	names := [...]string{"ContentTypeNone", "ContentTypeItem"}
	if e < ContentTypeNone || e > ContentTypeItem {
		return "Unknown"
	}

	return names[e]
}
